# Generated by Django 5.0 on 2026-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Scheduled publish time (required if status is 'scheduled')",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("scheduled", "Scheduled"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
