# Generated by Django 5.0.14 on 2026-03-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("kk", "Kazakh"),
                        ],
                        max_length=10,
                        verbose_name="Language",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Translation",
                "verbose_name_plural": "Category Translations",
                "unique_together": {("category", "language")},
            },
        ),
    ]
