# Generated by Django 5.0.14 on 2026-03-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "en"), ("ru", "ru"), ("kk", "kk")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
