# Generated by Django 5.0.14 on 2026-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_preferred_language_customuser_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Русский"), ("kk", "Қазақша")],
                default="en",
                max_length=10,
            ),
        ),
    ]
